# Generated by Django 5.1.1 on 2024-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('simple', 'Simple'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='simple', max_length=10, null=True),
        ),
    ]
