# Generated by Django 5.1.1 on 2024-09-21 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_have_product_active_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_af',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar_dz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ast',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_be',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ckb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_cs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_cy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_da',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_dsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_el',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_au',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_gb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_eo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_co',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_mx',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ni',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ve',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_et',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_eu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ga',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_gd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_gl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hsb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hu',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ia',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ig',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ind',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_io',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_is',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ja',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ka',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kab',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_km',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ml',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_my',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nb',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ne',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt_br',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sr_latn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_te',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_udm',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ug',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_af',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ar_dz',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ast',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_az',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_be',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_bg',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_bn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_br',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_bs',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ca',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ckb',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_cs',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_cy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_da',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_de',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_dsb',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_el',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en_au',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en_gb',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_eo',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_es',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_es_ar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_es_co',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_es_mx',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_es_ni',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_es_ve',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_et',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_eu',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_fa',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_fi',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_fr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_fy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ga',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_gd',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_gl',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_he',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_hi',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_hr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_hsb',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_hu',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_hy',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ia',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ig',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ind',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_io',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_is',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_it',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ja',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ka',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_kab',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_kk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_km',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_kn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ko',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_lb',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_lt',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_lv',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_mk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ml',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_mn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_mr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ms',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_my',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_nb',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ne',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_nl',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_nn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_os',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_pa',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_pl',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_pt',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_pt_br',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ro',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_sk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_sl',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_sq',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_sr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_sr_latn',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_sv',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_sw',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ta',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_te',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_tg',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_th',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_tk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_tr',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_tt',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_udm',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ug',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_uk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ur',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_uz',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_vi',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_zh_hans',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_zh_hant',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vid/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product'),
        ),
    ]
