# Generated by Django 5.1.1 on 2024-09-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_description_af_product_description_ar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Ratings',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AddField(
            model_name='product',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('simple', 'Simple')], default='simple', max_length=10, null=True),
        ),
    ]
